### ISSUE TITLE
Post-hoc test with ANOVA

### ISSUE THREAD

**Issue by lixiaopi1985** [ChiLiubio/microeco_tutorial#14]
Thank you for making this excellent package.

Based on the source code, Dunn's test seems to be the post hoc test method after ANOVA for trans_alpha and trans_diff. I just wanted to make sure this is correct. Additionally, is it possible to use Tukey's or other tests?

Xiaoping

**Comment by ChiLiubio** [comment]
Hi.
Yest. the current method is Duncan's new multiple range test from the function `duncan.test` in agricolae package. Thanks for your suggestion! More options will be considered in the future release.

Best
Chi

**Comment by ChiLiubio** [comment]
Hi. 
I have updated the microeco package in github and added the parameter `anova_post_test` in `cal_diff` function of `trans_alpha` class. As the document shows, the available options include "duncan.test", "HSD.test" and "LSD.test". Please select HSD.test for Tukey. The CRAN version will be released in the coming days. Thanks.

Chi

**Comment by lixiaopi1985** [comment]
> Hi. I have updated the microeco package in github and added the parameter `anova_post_test` in `cal_diff` function of `trans_alpha` class. As the document shows, the available options include "duncan.test", "HSD.test" and "LSD.test". Please select HSD.test for Tukey. The CRAN version will be released in the coming days. Thanks.
> 
> Chi

Thank you for your prompt responses and for adding more tests!
