### ISSUE TITLE
Error in creating a trans_abund object

### ISSUE THREAD

**Issue by Muneer111** [ChiLiubio/microeco_tutorial#8]
Hi @ChiLiubio 
Hope you are doing good
I am following the tutorial and getting through the codes and overcoming the errors.
Now While trying to plot a relative abundance, I am getting an error
I ran the code 
abundance<- trans_abund$new(dataset = dataset, taxrank = "Phylum", ntaxa = 10)
It gave an error object "trans_abund" not found.
However, I have calculated the abundance  using dataset$cal_abund()

**Comment by ChiLiubio** [comment]
Hi. Thanks. Please first load the package.
```
library(microeco)
```
The part of loading packages is omitted in each chapter.

**Comment by Muneer111** [comment]
Thank You
Solved

**Comment by Muneer111** [comment]
Hi Sir 
Hope you are fine and doing good
Please suggest 
Error in if (any(apply(otu_table, 1, sum) == 0)) { : 
  missing value where TRUE/FALSE needed

**Comment by Muneer111** [comment]
Hi sir
Hope I trust you are well.
While running the code 
t1$cal_autocor()
 I am getting the plot, 
but at the same time 
using this  **"t1$cal_autocor(group ="Treatment")**"code gives me the error 
**data` must be uniquely named but has duplicate columns
Run `rlang::last_trace()` to see where the error occurred.**
Attached is my env_data an sample_info file 
Kindly suggest 
thanks in advance 
Best Regards
[env_data.csv](https://github.com/ChiLiubio/microeco_tutorial/files/11554614/env_data.csv)
[sample_info.csv](https://github.com/ChiLiubio/microeco_tutorial/files/11554615/sample_info.csv)

**Comment by ChiLiubio** [comment]
Hi. Please attach your microtable object instead of each file as the tutorial shows(https://chiliubio.github.io/microeco_tutorial/notes.html#save-function), as the data import is critical to the check. Please also provide the steps creating `t1`.

**Comment by Muneer111** [comment]
Thank You Sir
I created the t1 step, by got the same error
[otu_table.csv](https://github.com/ChiLiubio/microeco_tutorial/files/11564367/otu_table.csv)
Please suggest
Thanks and Regards

**Comment by ChiLiubio** [comment]
Please attach your R script that I can use to totally reproduce your error.

**Comment by Muneer111** [comment]
Please find
[library.docx](https://github.com/ChiLiubio/microeco_tutorial/files/11564435/library.docx)

**Comment by ChiLiubio** [comment]
In your script `t1 <- trans_env$new(dataset = new_test, env_cols = 2:8)`, only the columns 4 to 8 in your `sample_table` are numeric values that can be used, why you select 2:8? I have check the steps with 4:8, all are fine.
```
t1 <- trans_env$new(dataset = new_test, env_cols = 4:8)
t1$cal_diff(method = "anova", group = "Group")
tmp <- list()
library(ggplot2)
library(GGally)
for(i in colnames(t1$data_env)){
  tmp[[i]] <- t1$plot_diff(measure = i, add_sig_text_size = 5, xtext_size = 12) + theme(plot.margin = unit(c(0.1, 0, 0, 1), "cm"))
}
t1$cal_autocor()
t1$cal_autocor(group ="Treatment")
```

**Comment by Muneer111** [comment]
Thank You So much
But I have one confusion, while looking at my sample_table and env-date table 
I can see only three columns (A, B, C) and six (A, B, C, D, E, F). 
in case of env-data column one is sample ID,remaing columns are 5
Therefore how to select (env_cols = 4:8).
This confused me previously as well.
kindly guide
Thanks and Best regards

**Comment by ChiLiubio** [comment]
You create a new microtabl object `new_test`, in which all the metadata variables can be selected. 
```
View(new_test$sample_table)
```
So the `new_test` has all the basic data.

**Comment by Muneer111** [comment]
Thank You so much sir

**Comment by Muneer111** [comment]
Dear Sir
Again now I want to plot lefse
and after running the two codes I am getting error
> t1 <- trans_diff$new(dataset = dataset, method = "lefse", group = "Group", alpha = 0.01, lefse_subgroup = NULL)
Start Kruskal-Wallis rank sum test for Group ...
3 taxa found significant ...
After P value adjustment, 0 taxa found significant ...
Error in initialize(...) : 
  No significant feature found! To disable p value adjustment, please use p_adjust_method = "none"!
> t1 <- trans_diff$new(dataset = dataset, p_adjust_method = "none", group = "Group", alpha = 0.01, lefse_subgroup = NULL)
Start Kruskal-Wallis rank sum test for Group ...
3 taxa found significant ...
After P value adjustment, 3 taxa found significant ...
**Error in tapply(LD, group_vec_lda, mean) : 
  arguments must have same length**
Kindly suggest
Thanks in advance
Regards

**Comment by ChiLiubio** [comment]
Hi @Muneer111 
Could you please save your dataset and send me to have a try?. Please save the dataset following this tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the zip file.

Chi

**Comment by Muneer111** [comment]
Thank You Sir
I don't know whether I saved the data perfectly or not, but here I am attaching it.
Please have a look
thanks and Regards
[Lefse_2.zip](https://github.com/ChiLiubio/microeco_tutorial/files/11649572/Lefse_2.zip)

**Comment by Muneer111** [comment]
Hello Dear Sir
Please help out

**Comment by ChiLiubio** [comment]
I thought you have solved it as I see you closed this issue. 
Please find out the file in the R working directory. If you are not sure where it is, please use `getwd()` command.

**Comment by Muneer111** [comment]
Dear Sir 
Please find this and let me know whether it works or not
Thanks and Regards 
[Lefse_2.zip](https://github.com/ChiLiubio/microeco_tutorial/files/11685609/Lefse_2.zip)

**Comment by ChiLiubio** [comment]
Hi. The probable reason is too few significant features are found for the five groups. I will test it further. A temporary solution is to adjust the alpha with 0.05.
```
t1 <- trans_diff$new(dataset = dataset, p_adjust_method = "none", group = "Group", alpha = 0.05, lefse_subgroup = NULL)
t1$plot_diff_bar(threshold = 2)
```

**Comment by Muneer111** [comment]
Dear Sir
I trust you are well
Thank you for your help.
I will check out by adjusting the alpha with 0.05.
Have you tracked for other solutions.
Secondly, I was trying to loo for the function and installed file2meco package
but it gave error 
Error: package or namespace load failed for ‘file2meco’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘rhdf5’
Please suggest

**Comment by ChiLiubio** [comment]
Please use the file2meco installation way here (https://github.com/ChiLiubio/file2meco). I will tell you after I trace back the reason.

**Comment by ChiLiubio** [comment]
Hi @Muneer111 
Sorry for the delay. I have throughly checked the codes and find this is a minor bug of feature name when there is only one feature in the LDA analysis of paired groups. This case may occur when few significant features are generated for the following LDA algorithm. I have fixed it and updated the package in github. You can try again by updating the package from github.
```
install.packages("devtools")
devtools::install_github("ChiLiubio/microeco")
library(microeco)
set.seed(1)
t1 <- trans_diff$new(dataset = dataset, p_adjust_method = "none", group = "Group", alpha = 0.01, lefse_subgroup = NULL)
t1$plot_diff_bar()
```
Thanks for your finding.

Best,
Chi

**Comment by Muneer111** [comment]
Hi Sir
Than you for your help
While I tried to run this but got an error
install.packages("devtools")
devtools::install_github("ChiLiubio/microeco")
library(microeco)
set.seed(1)
t1 <- trans_diff$new(dataset = dataset, p_adjust_method = "none", group = "Group", alpha = 0.01, lefse_subgroup = NULL)
Start Kruskal-Wallis rank sum test for Group ...
5 taxa found significant ...
After P value adjustment, 5 taxa found significant ...
Minimum LDA score: 1.33445088793158 maximum LDA score: 1.33445088793158
Taxa abundance table is stored in object$res_abund ...
lefse analysis result is stored in object$res_diff ...
There were 50 or more warnings (use warnings() to see the first 50)
t1$plot_diff_bar()
got only 1 group 
![Lefse 18S 1906](https://github.com/ChiLiubio/microeco_tutorial/assets/76723877/d5f7c45d-08fa-49a8-b3f7-1529d66252f7)


Then in case of 18S again I am missing one group after running the code 
![Lefse 18S](https://github.com/ChiLiubio/microeco_tutorial/assets/76723877/4d10deb9-2db8-4a45-a815-e5e8624f79ad)
 


Finally again running some different datasets I am getting and unexpected error 
on the code 
**dataset <- microtable$new(otu_table = otu_table)**
NA taxa are removed from the otu_table, as the abundance is 0 ...
Error in if (any(apply(otu_table, 2, sum) == 0)) { : 
  missing value where TRUE/FALSE needed

Kindly suggest 
thanks in advance

**Comment by Muneer111** [comment]
Hi again
Finally again running some different datasets I am getting and unexpected error
on the code
dataset <- microtable$new(otu_table = otu_table)
NA taxa are removed from the otu_table, as the abundance is 0 ...
Error in if (any(apply(otu_table, 2, sum) == 0)) { :
missing value where TRUE/FALSE needed
This I sorted but this time around it showed the number of OTUs removed also, as previously it was not showing the same.
thanks

**Comment by ChiLiubio** [comment]
Hi. Please check your data. I guess there are NA in your dataset leading to such an error.
For the upper case 'got only 1 group', the reason is there are no significant enriched features (maybe also with high LDA) in other groups. So you can go through the table `t1$res_diff` to double check the result.

**Comment by Muneer111** [comment]
Hi again
Hope you are fine and doing good
Well as suggested by you, I have ran t1$res_diff and doubled checked the results, it showed many are insignificant.
In that case how can we discuss lefse and can we present them in results or not.
thanks and regards

**Comment by ChiLiubio** [comment]
Hi. The significance comes from the Kruskal-Wallis test, which is the first step in the lefse analysis. So the key point may be the explanation on why there are no significane among your groups with KW test.
